### ISSUE TITLE
Project Improvement Suggestion

### ISSUE THREAD

**Issue by skyv26** [eliloq/QR-Code#1]
#### 1️⃣ **Heading Hierarchy Matters**  
Ensure you follow proper **heading hierarchy** in your project. Currently, the primary heading uses `<h5>`, which isn't semantically appropriate for a main title. Instead, use `<h1>` for the primary heading to maintain correct accessibility and structure. 🏗️

---

#### 2️⃣ **Stick to the Style Guide 🎨**  
To make your app closely match the design:  
- Follow the **style guide** precisely. For example, the project specifies the use of the `'Outfit'` font family.  
- In the `setting.css` file, I noticed you used an incorrect file path. Replace `Fonts` with `fonts` to ensure the font loads properly. This small fix will make a big difference in achieving the desired appearance. ✨

### Correct Path
```css

@font-face {
  font-family: Outfit;
  src: url(./fonts/Outfit-Regular.eot);
  src: url(./fonts/Outfit-Regular.ttf);
  src: url(./fonts/Outfit-Regular.woff);
  src: url(./fonts/Outfit-Regular.woff2);
}
```

---

#### 3️⃣ **Responsive Design for Larger Screens 📱➡️💻**  
The design doesn't seem fully responsive on larger screens (above **1440px** breakpoints). Consider optimizing the layout and styles to handle these resolutions. This will ensure a seamless experience across devices, including ultra-wide monitors. 🖥️

---

### Keep up the great work! 💪 If you address these areas, your project will look even more polished and professional. 🎉
